:qmatrix:
  include:
    - language: node_js
      node_js:
          - "14"
      install:
          - npm install vuepress
      script:
          - pyenv global system 3.6.7
          - pip3 install -e .
          - pip3 install -r docs-requirements.txt
          - python3.6 docs/.vuepress/_reference/autogen.py
          - vuepress build docs
      after_failure:
        - rm -rf /home/travis/machinable/node_modules
        - cat /home/travis/.npm/_logs/*-debug.log
      cache:
          directories:
              - "node_modules"
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/.vuepress/dist
        github_token: $GITHUB_TOKEN
        repo: machinable-org/machinable
        keep_history: false
        target_branch: gh-pages
        on:
          branch: master
    - language: python
      python:
        - 3.6
        - 3.7
        - 3.8
      install:
        - pip install -r test-requirements.txt
        - pip install --upgrade pytest
        - pip install -e .
      before_script: cd tests
      script:
        - pytest
      before_deploy:
        - cd /home/travis/build/machinable-org/machinable
      deploy:
        skip_cleanup: true
        provider: pypi
        user: "__token__"
        password: $PYPI_TOKEN
        on:
          tags: true
          python: 3.6
notifications:
    email: false